name: Merge latest main to branches
on:
  push:
    branches:
      - force_merge
env:
    ROOT_BRANCH_NAME: master
    branch_NG: testa, force-merge
jobs:
  Rebase-All:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Merging  branches ${{ env.BRANCHES_TO_REBASE }} with ${{ env.ROOT_BRANCH_NAME }}"
      - name: Checking out repository code into workspace...
        uses: actions/checkout@v3
      - name: Begin merge process...
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo "Fetching latest..."
          git fetch origin
          git checkout ${{ env.ROOT_BRANCH_NAME }}
          git pull --allow-unrelated-histories
          echo "Beginning merge...."
          for branch in $(git for-each-ref --format='%(refname:short)' refs/heads/); do
            if [[ "$branch_NG" == *"$branch"* ]]; then
              echo "SKIPPING $branch"
              continue
            fi
            git checkout $branch
            git pull --allow-unrelated-histories
            git merge $ROOT_BRANCH_NAME --no-edit || { git add -u . && git commit --no-edit ;}
            git push
            echo "Merge SUCCEEDED for branch $branch"
          done