name: Rebase Branches
on:
  push:
    branches:
      - rebase_all
env:
    ROOT_BRANCH_NAME: master
    BRANCHES_TO_REBASE: gh-actions-test,testa,testb

jobs:
  Rebase-All:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Rebasing branches $BRANCHES_TO_REBASE with $ROOT_BRANCH_NAME"
      - name: First Check out repository code
        uses: actions/checkout@v2
      - run: echo "Fetching latest..."
      - run: git fetch origin
      - run: echo "Beginning rebase..."
      - run: |
          IFS=","
          for branch in $BRANCHES_TO_REBASE; do
            if [$? -ne 0]
            then
              git rebase --abort
            fi
            git rebase origin/$ROOT_BRANCH_NAME origin/$branch
          done
