name: Merge latest main to branches
on:
  push:
    branches:
      - force_merge
env:
    ROOT_BRANCH_NAME: master
    BRANCHES_TO_REBASE: gh-actions-test,testa,testb
jobs:
  Rebase-All:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Merging  branches ${{ env.BRANCHES_TO_REBASE }} with ${{ env.ROOT_BRANCH_NAME }}"
      - name: Checking out repository code into workspace...
        uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo "Fetching latest..."
          git fetch origin
          git checkout ${{ env.ROOT_BRANCH_NAME }}
          git pull
          echo "Beginning merge...."
          IFS=","
          for branch in $BRANCHES_TO_REBASE; do
            { git checkout $branch \
              && git pull \
              && git merge $ROOT_BRANCH_NAME; git add -u . \
              && git commit --no-edit \
              && git push \
              && echo "Merge SUCCEEDED for branch $branch" ; }
          done