name: Rebase Branches
on:
  push:
    branches:
      - rebase_all
env:
    ROOT_BRANCH_NAME: master
    BRANCHES_TO_REBASE: gh-actions-test,testa,testb
jobs:
  Rebase-All:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Rebasing branches ${{ env.BRANCHES_TO_REBASE }} with ${{ env.ROOT_BRANCH_NAME }}"
      - name: Checking out repository code into workspace...
        uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: echo "Fetching latest..."
      - run: git fetch origin
      - run: git checkout ${{ env.ROOT_BRANCH_NAME }}
      - run: git pull
      - run: echo "Beginning rebase..."
      - run: |
          IFS=","
          for branch in $BRANCHES_TO_REBASE; do
            { git checkout $branch  && git pull && git rebase $ROOT_BRANCH_NAME && git push && echo "Rebase SUCCEEDED for branch $branch" ;} || { echo "Rebase FAILED for branch $branch" && git rebase --abort ; }
          done
