name: Rebase Branches
on:
  push:
    branches:
      - rebase_all
env:
    ROOT_BRANCH_NAME: main
    BRANCHES_TO_REBASE: gh-actions-test, testa, testb

jobs:
  Rebase-All:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Rebasing branches $BRANCHES_TO_REBASE with $ROOT_BRANCH_NAME"
      - run: echo "Fetching latest..."
      - run: git fetch
      - run: echo "Beginning rebase..."
      - run: |
          for branch in "$BRANCHES_TO_REBASE"; do
            echo "Branch name: $branch"
          done
